[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "never"

[variables]
FLASK_ENV = "production"
SECRET_KEY = "dolkim85-smartfarm-production-key"
UPLOAD_FOLDER = "./uploads"
PYTHON_VERSION = "3.11"
PYTHONPATH = "/app" 